#!/usr/bin/env node
/**
 * Accessibility Audit — Report Generator
 *
 * Reads findings.jsonl (produced by audit-merge.mjs) and generates a
 * summary.md report with severity breakdown, top fixes, per-page
 * findings, and cross-engine confidence classification.
 *
 * Usage:
 *   node audit-report.mjs --out=./audit-output
 */
import { writeFileSync, mkdirSync } from 'fs';
import { join, resolve } from 'path';
import { arg, handleVersionFlag, loadJsonl } from './lib/shared.mjs';

handleVersionFlag('audit-report');

// ── Help ───────────────────────────────────────────────────────
if (process.argv.includes('--help') || process.argv.includes('-h')) {
  console.log(`
Usage:
  node audit-report.mjs --out=DIR

Arguments:
  --out     Directory containing findings.jsonl (default: ./audit-output)

Input:
  findings.jsonl    Merged, deduplicated findings produced by audit-merge.mjs.
                    This script reads it as canonical — run audit-merge.mjs
                    first to populate it from per-engine files.

Output:
  summary.md        Structured audit summary report with severity breakdown,
                    per-page findings, top fixes, and multi-engine agreement.
`);
  process.exit(0);
}

const OUT = resolve(arg('out', './audit-output'));
mkdirSync(OUT, { recursive: true });

// findings.jsonl is produced by audit-merge.mjs — already cross-engine
// deduplicated. We read it as canonical; do not re-merge here.
const findingsPath = join(OUT, 'findings.jsonl');
let findings = loadJsonl(findingsPath);

// Back-compat: if findings.jsonl is missing but per-engine files exist,
// point the user at audit-merge.mjs instead of silently mixing half the
// data.
if (findings.length === 0) {
  const axeOnly = loadJsonl(join(OUT, 'axe-results.jsonl'));
  if (axeOnly.length > 0) {
    console.warn('Warning: findings.jsonl is empty but engine outputs exist.');
    console.warn('Run audit-merge.mjs first to produce the canonical findings file.');
  }
}

if (findings.length === 0) {
  console.log('No findings in input files. Generating clean summary.');
  const cleanMd = `# Accessibility Audit Summary\n\n**Generated:** ${new Date().toISOString()}\n**Total findings:** 0\n\nNo accessibility violations detected by automated tools. Manual testing may still be required for criteria that cannot be automated.\n\n---\n\n*Generated by audit-report.mjs*\n`;
  writeFileSync(join(OUT, 'summary.md'), cleanMd);
  console.log(`Summary written to ${join(OUT, 'summary.md')}`);
  process.exit(0);
}

// Escape pipe chars so they don't break markdown tables when a title
// or evidence contains `|`. Axe's test titles sometimes include pipes
// (e.g. "elements should have labels | names").
function mdCell(s) {
  if (s === null || s === undefined) return '-';
  return String(s).replace(/\|/g, '\\|').replace(/\n/g, ' ');
}

const fromEachEngine = findings.reduce((m, f) => {
  const src = (f.source || '').split('+')[0] || 'manual';
  m[src] = (m[src] || 0) + 1;
  return m;
}, {});
console.log(`Loaded ${findings.length} findings (${Object.entries(fromEachEngine).map(([k,v]) => `${v} ${k}`).join(', ')})`);

// ── Analysis ───────────────────────────────────────────────────
const severityOrder = ['critical', 'serious', 'moderate', 'minor', 'pass'];

const bySeverity = {};
const byPage = {};
const bySC = {};
const byPhase = {};

for (const f of findings) {
  const sev = f.severity || 'unknown';
  bySeverity[sev] = (bySeverity[sev] || 0) + 1;

  const page = f.page || 'unknown';
  if (!byPage[page]) byPage[page] = [];
  byPage[page].push(f);

  const sc = f.sc || 'unknown';
  if (!bySC[sc]) bySC[sc] = [];
  bySC[sc].push(f);

  const phase = f.phase || 'unknown';
  byPhase[phase] = (byPhase[phase] || 0) + 1;
}

const issues = findings.filter(f => f.severity !== 'pass');
const passes = findings.filter(f => f.severity === 'pass');

// Top fixes: group issues by SC, rank by total severity weight
const severityWeight = { critical: 4, serious: 3, moderate: 2, minor: 1 };
const scImpact = {};
for (const f of issues) {
  const sc = f.sc || 'unknown';
  scImpact[sc] = (scImpact[sc] || 0) + (severityWeight[f.severity] || 1);
}
const topFixes = Object.entries(scImpact)
  .sort((a, b) => b[1] - a[1])
  .slice(0, 10);

// ── Generate summary.md ────────────────────────────────────────
let md = `# Accessibility Audit Summary\n\n`;
md += `**Generated:** ${new Date().toISOString()}\n`;
md += `**Total findings:** ${findings.length} (${issues.length} issues, ${passes.length} passes)\n\n`;

// Severity breakdown
md += `## Findings by Severity\n\n`;
md += `| Severity | Count |\n|---|---|\n`;
for (const sev of severityOrder) {
  if (bySeverity[sev]) {
    md += `| ${sev} | ${bySeverity[sev]} |\n`;
  }
}
md += '\n';

// Phase breakdown
md += `## Findings by Phase\n\n`;
md += `| Phase | Count |\n|---|---|\n`;
for (const [phase, count] of Object.entries(byPhase).sort((a, b) => b[1] - a[1])) {
  md += `| ${phase} | ${count} |\n`;
}
md += '\n';

// Top fixes
if (topFixes.length > 0) {
  md += `## Top Fixes by Impact\n\n`;
  md += `Ranked by cumulative severity weight across all pages.\n\n`;
  md += `| Rank | WCAG SC | Impact Score | Issue Count |\n|---|---|---|---|\n`;
  topFixes.forEach(([sc, weight], i) => {
    const count = bySC[sc]?.filter(f => f.severity !== 'pass').length || 0;
    const name = bySC[sc]?.[0]?.sc_name || sc;
    md += `| ${i + 1} | ${mdCell(`${sc} ${name}`)} | ${weight} | ${count} |\n`;
  });
  md += '\n';
}

// Per-page breakdown
md += `## Findings by Page\n\n`;
for (const [page, pageFindings] of Object.entries(byPage).sort()) {
  const pageIssues = pageFindings.filter(f => f.severity !== 'pass');
  const pagePasses = pageFindings.filter(f => f.severity === 'pass');
  md += `### ${page}\n\n`;
  md += `${pageIssues.length} issues, ${pagePasses.length} passes\n\n`;

  if (pageIssues.length > 0) {
    md += `| ID | SC | Severity | Title |\n|---|---|---|---|\n`;
    // Cap to 100 per page — large sites with engines producing per-node
    // findings could otherwise blow up the report.
    for (const f of pageIssues.slice(0, 100)) {
      md += `| ${mdCell(f.id)} | ${mdCell(f.sc)} | ${mdCell(f.severity)} | ${mdCell(f.title || (f.observed || '').substring(0, 60))} |\n`;
    }
    if (pageIssues.length > 100) md += `| ... | (${pageIssues.length - 100} more — see findings.jsonl) | | |\n`;
    md += '\n';
  }
}

// Pass inventory. On pages with IBA's 1800+ passes-per-page, this section
// can explode summary.md into tens of MB. Cap at 200 to keep the report
// readable; users wanting the full list should query findings.jsonl
// directly with jq.
if (passes.length > 0) {
  md += `## Pass Inventory\n\n`;
  md += `These checks passed and serve as regression guards.\n\n`;
  if (passes.length > 200) {
    md += `_Showing first 200 of ${passes.length} passes. For the complete list, query \`findings.jsonl\` with \`jq 'select(.severity=="pass")'\`._\n\n`;
  }
  md += `| ID | SC | Page | Check |\n|---|---|---|---|\n`;
  for (const f of passes.slice(0, 200)) {
    md += `| ${mdCell(f.id)} | ${mdCell(f.sc)} | ${mdCell(f.page)} | ${mdCell(f.title || (f.observed || '').substring(0, 60))} |\n`;
  }
  md += '\n';
}

// Confidence breakdown — multi-engine agreement is the strongest
// automated signal. A finding confirmed by 2+ engines is much less
// likely to be a false positive than a single-engine result.
const multiEngineIssues = issues.filter(f => Array.isArray(f.sources) && f.sources.length >= 2);
const singleEngineIssues = issues.filter(f => !(Array.isArray(f.sources) && f.sources.length >= 2));

md += `## Confidence\n\n`;
md += `| Classification | Count | What it means |\n|---|---:|---|\n`;
md += `| Multi-engine agreement | ${multiEngineIssues.length} | ≥2 engines flagged — high confidence |\n`;
md += `| Single-engine | ${singleEngineIssues.length} | One engine flagged — verify before reporting |\n`;
if (issues.length > 0) {
  const pct = Math.round((multiEngineIssues.length / issues.length) * 100);
  md += `\nMulti-engine confirmation rate: **${pct}%** of issues.\n\n`;
  md += `Low confirmation rates are normal — engines have complementary coverage more than overlapping coverage. Review single-engine findings with the rule ID and evidence to decide confidence.\n\n`;
}

if (multiEngineIssues.length > 0) {
  md += `### High-confidence issues (multi-engine)\n\n`;
  md += `| ID | SC | Severity | Engines | Title |\n|---|---|---|---|---|\n`;
  for (const f of multiEngineIssues.slice(0, 30)) {
    md += `| ${mdCell(f.id)} | ${mdCell(f.sc)} | ${mdCell(f.severity)} | ${mdCell((f.sources || []).join(', '))} | ${mdCell((f.title || '').substring(0, 60))} |\n`;
  }
  if (multiEngineIssues.length > 30) md += `| ... | (${multiEngineIssues.length - 30} more) | | | |\n`;
  md += '\n';
}

// Source breakdown (engine attribution, atomized)
const atomicSources = {};
for (const f of findings) {
  const src = f.source || 'manual';
  for (const atom of src.split('+')) {
    atomicSources[atom] = (atomicSources[atom] || 0) + 1;
  }
}
if (Object.keys(atomicSources).length > 1) {
  md += `## Findings by Engine\n\n`;
  md += `Each engine is counted once per finding it contributed to (so a multi-engine finding increments multiple rows).\n\n`;
  md += `| Engine | Findings |\n|---|---:|\n`;
  for (const [src, count] of Object.entries(atomicSources).sort((a, b) => b[1] - a[1])) {
    md += `| ${src} | ${count} |\n`;
  }
  md += '\n';
}

md += `---\n\n*Generated by audit-report.mjs from findings.jsonl*\n`;

// ── Write ──────────────────────────────────────────────────────
const outPath = join(OUT, 'summary.md');
writeFileSync(outPath, md);
console.log(`Summary written to ${outPath}`);
